DIVLM_TRAIN_PROJECT = "DivLM_train"
DIVLM_TEST_PROJECT = "DivLM_test"

DEFAULT_SEED = 42
CPT_SEED = 3407
JUDGE_MODEL_NAME = "google/gemma-3-12b-it"
SENTENCE_ENCODER_MODEL = "sentence-transformers/all-mpnet-base-v2"

GROUP_SIZE = 10
TRAIN_SIZE = 3000
MAX_NEW_TOKENS = 700
MAX_PROMPT_LENGTH = 2048
TARGET_WORDS = 500
GEN_TEMPERATURE = 1.0
GEN_TOP_P = 0.95
GEN_TOP_K = 50
GEN_REPETITION_PENALTY = 1.1
EVAL_GENERATION_BATCH_SIZE = 100
TRAIN_GENERATION_BATCH_SIZE_SINGLE_GPU = 50
TRAIN_GENERATION_BATCH_SIZE_MULTI_GPU = 200

QUALITY_TAU = 2.0 / 3.0
GROUP_QUALITY_TAU = 0.91
INVALID_R_QUAL = -1.0
R_DIV_NORMALIZER = 4.0
ENTITY_CLIP_U = 4.0
ENTITY_H = 5.0
LENGTH_PENALTY_TARGET_WORDS = 500
JUDGE_BATCH_SIZE = 10

GENRE_COUNT = 9
TONE_COUNT = 3
STYLE_COUNT = 3

GRPO_EPOCHS = 2.0
GRPO_LEARNING_RATE = 4e-5
GRPO_BETA = 0.001
GRPO_MAX_GRAD_NORM = 0.3
GRPO_PER_DEVICE_TRAIN_BATCH_SIZE = 5
GRPO_GRADIENT_ACCUMULATION_STEPS = 1
REWARD_PRINT_EVERY = 100
MONITOR_CHECK_EVERY = 5
MONITOR_MAX_RESTARTS = 2
MONITOR_ACCEPT_AFTER_FRACTION = 0.8

CPT_EPOCHS = 1.0
CPT_MAX_SEQ_LENGTH = 1024
CPT_LEARNING_RATE = 1e-4
CPT_WARMUP_RATIO = 0.08
CPT_PER_DEVICE_TRAIN_BATCH_SIZE = 16
CPT_GRADIENT_ACCUMULATION_STEPS = 1
CPT_LORA_R = 32
CPT_LORA_ALPHA = 32
CPT_LORA_DROPOUT = 0.0
CPT_WEIGHT_DECAY = 0.1
CPT_MAX_GRAD_NORM = 1.0
CPT_LOGGING_STEPS = 10
CPT_SAVE_STEPS = 500
CPT_SAVE_TOTAL_LIMIT = 2
